name: 'lol_analytics'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_modules"

# YENİ DÜZEN:
models:
  lol_analytics:
    staging:
      +materialized: view      # dbt_ekaramanli içinde bir view olacak
    intermediate:
      +materialized: view      # dbt_ekaramanli içinde bir view olacak
    marts:
      +materialized: table     # dbt_ekaramanli içinde fiziki bir tablo olacak